version: '3.8'

services:
  redis-node-1:
    image: redis:6.2
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-node/redis-node-1:/data

  redis-node-2:
    image: redis:6.2
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - ./redis-node/redis-node-2:/data

  redis-node-3:
    image: redis:6.2
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6381:6379"
    volumes:
      - ./redis-node/redis-node-3:/data

  redis-node-4:
    image: redis:6.2
    container_name: redis-node-4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6382:6379"
    volumes:
      - ./redis-node/redis-node-4:/data

  redis-node-5:
    image: redis:6.2
    container_name: redis-node-5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6383:6379"
    volumes:
      - ./redis-node/redis-node-5:/data

  redis-node-6:
    image: redis:6.2
    container_name: redis-node-6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6384:6379"
    volumes:
      - ./redis-node/redis-node-6:/data
