INSERT INTO INVENTORY(PRODUCT_NAME, STOCK_QUANTITY, LAST_UPDATED) VALUES('바나나', 99999, CURRENT_TIMESTAMP);
INSERT INTO INVENTORY(PRODUCT_NAME, STOCK_QUANTITY, LAST_UPDATED) VALUES('사과', 99999, CURRENT_TIMESTAMP);
INSERT INTO INVENTORY(PRODUCT_NAME, STOCK_QUANTITY, LAST_UPDATED) VALUES('수박', 99999, CURRENT_TIMESTAMP);