DROP TABLE IF EXISTS INVENTORY;
CREATE TABLE INVENTORY (
   INVENTORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,       -- 상품 ID
   PRODUCT_NAME VARCHAR(255) NOT NULL,       -- 상품 이름
   STOCK_QUANTITY INT NOT NULL DEFAULT 0,    -- 재고 수량
   LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- 마지막 업데이트 시간
);